version: '3.9'

services:
  backend:
    build: ./back
    container_name: spring_backend
    ports:
      - "8080:8080"
    networks:
      - minha-rede

  frontend:
    build: ./front
    container_name: next_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - minha-rede

networks:
  minha-rede:
    external: true